-- MySQL Script generated by MySQL Workbench
-- Tue May  5 15:37:04 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CartnetAdresse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CartnetAdresse` ;

-- -----------------------------------------------------
-- Schema CartnetAdresse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CartnetAdresse` DEFAULT CHARACTER SET utf8 ;
USE `CartnetAdresse` ;

-- -----------------------------------------------------
-- Table `CartnetAdresse`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CartnetAdresse`.`users` ;

CREATE TABLE IF NOT EXISTS `CartnetAdresse`.`users` (
  `idUsers` INT NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(11) NOT NULL,
  `lastLogin` DATE NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CartnetAdresse`.`user_contact`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CartnetAdresse`.`user_contact` ;

CREATE TABLE IF NOT EXISTS `CartnetAdresse`.`user_contact` (
  `idUsers` INT NOT NULL,
  `idContact` INT NOT NULL,
  INDEX `fk_table1_users_idx` (`idUsers` ASC) VISIBLE,
  INDEX `fk_table1_users1_idx` (`idContact` ASC) VISIBLE,
  CONSTRAINT `fk_table1_users`
    FOREIGN KEY (`idUsers`)
    REFERENCES `CartnetAdresse`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_table1_users1`
    FOREIGN KEY (`idContact`)
    REFERENCES `CartnetAdresse`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
