-- MySQL Script generated by MySQL Workbench
-- Tue May  5 16:26:31 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema CarnetAdresse
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `CarnetAdresse` ;

-- -----------------------------------------------------
-- Schema CarnetAdresse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `CarnetAdresse` DEFAULT CHARACTER SET utf8 ;
USE `CarnetAdresse` ;

-- -----------------------------------------------------
-- Table `CarnetAdresse`.`roles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CarnetAdresse`.`roles` ;

CREATE TABLE IF NOT EXISTS `CarnetAdresse`.`roles` (
  `idRoles` INT NOT NULL AUTO_INCREMENT,
  `roleName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRoles`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `CarnetAdresse`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `CarnetAdresse`.`users` ;

CREATE TABLE IF NOT EXISTS `CarnetAdresse`.`users` (
  `idUsers` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `salt` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `phoneNumber` VARCHAR(11) NOT NULL,
  `lastLogin` DATE NULL,
  `roles_idRoles` INT NOT NULL,
  PRIMARY KEY (`idUsers`),
  UNIQUE INDEX `username_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_users_roles_idx` (`roles_idRoles` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles`
    FOREIGN KEY (`roles_idRoles`)
    REFERENCES `CarnetAdresse`.`roles` (`idRoles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
